const SPOTS = [
  // ===== ITALIAN =====
  { cat: 'italian', name: "La Stella", rating: 4.8, count: 2554, price: 3, address: "2330 Flora St, Arts District", note: "Italian, Arts District. Elegant but not stuffy. Sommelier on site. Butternut squash ravioli is the order.", maps: "https://www.google.com/maps/search/?api=1&query=La+Stella%2C+2330+Flora+St%2C+Arts+District%2C+Dallas%2C+TX", menu: "https://www.lastellatx.com/", tags: ["Arts District", "Date-worthy"] },
  { cat: 'italian', name: "The Charles", rating: 4.7, count: 834, price: 2, address: "1632 Market Center Blvd", note: "Design District. Italian, romantic. Loud on weekends — book a weekday for actual conversation.", maps: "https://www.google.com/maps/search/?api=1&query=The+Charles%2C+1632+Market+Center+Blvd%2C+Dallas%2C+TX", menu: "https://thecharlesdallas.com/", tags: ["Design District", "Romantic"] },
  { cat: 'italian', name: "Enoteca Italia", rating: 4.7, count: 858, price: 3, address: "3102 Oak Lawn Ave #116, Oak Lawn", note: "Cozy neighborhood Italian. Ask Frank for the special espresso martini. Pollo Piccata is the move. Closed Mondays. Great date night spot — books up Fri/Sat.", maps: "https://www.google.com/maps/search/?api=1&query=Enoteca+Italia%2C+3102+Oak+Lawn+Ave+%23116%2C+Oak+Lawn%2C+Dallas%2C+TX", menu: "https://enotecaitalia.com/", tags: ["Date night", "Cozy"] },
  { cat: 'italian', name: "Due' Cucina (Lakewood)", rating: 4.8, count: 1005, price: 2, address: "1900 Abrams Pkwy, Lakewood", note: "Build-your-own pasta — pick your noodle, sauce, protein. Fresh handmade pasta, affordable, great cannoli. Small space, not for big groups. Family-owned vibe.", maps: "https://www.google.com/maps/search/?api=1&query=Due%27+Cucina+%28Lakewood%29%2C+1900+Abrams+Pkwy%2C+Lakewood%2C+Dallas%2C+TX", menu: "https://duecucina.com/", tags: ["Affordable", "Build-your-own", "Lakewood"] },
  { cat: 'italian', name: "Sprezza", rating: 4.5, count: 329, price: 2, address: "4010 Maple Ave, Oak Lawn", note: "Chef Ryan's spot. Daily-changing menu, fresh handmade pasta, sweet potato gnocchi standout. Wine list is by price category — ask the staff to navigate. Books up.", maps: "https://www.google.com/maps/search/?api=1&query=Sprezza%2C+4010+Maple+Ave%2C+Oak+Lawn%2C+Dallas%2C+TX", menu: "https://www.sprezzadallas.com/", tags: ["Daily menu", "Wine"] },

  // ===== PIZZA =====
  { cat: 'pizza', name: "Mister O1 Extraordinary Pizza", rating: 4.9, count: 4889, price: 2, address: "3838 Oak Lawn Ave, Turtle Creek", note: "Hands-down top pizza in Dallas. 4.9 over 4,800 reviews. The Mimmo with basil, ranch, and honey is the move. Thin crust, electric oven, perfect char.", maps: "https://www.google.com/maps/search/?api=1&query=Mister+O1+Extraordinary+Pizza%2C+3838+Oak+Lawn+Ave%2C+Turtle+Creek%2C+Dallas%2C+TX", menu: "https://www.mistero1.com/", tags: ["Top pick", "Thin crust"] },
  { cat: 'pizza', name: "D.L. Mack's", rating: 5.0, count: 320, price: 2, address: "3699 McKinney Ave, Uptown", note: "Tavern-style Chicago pizza. 5.0 stars. Chicken parm is the standout side. Great Uptown spot for casual dinner.", maps: "https://www.google.com/maps/search/?api=1&query=D.L.+Mack%27s%2C+3699+McKinney+Ave%2C+Uptown%2C+Dallas%2C+TX", menu: "https://dlmacks.com/", tags: ["Chicago style", "Uptown"] },
  { cat: 'pizza', name: "Bellatrino Pizzeria", rating: 4.9, count: 3125, price: 2, address: "920 S Harwood St, Farmers Market", note: "Inside Dallas Farmers Market. Wood-fired Neapolitan pizza. Great for a casual lunch in a fun environment.", maps: "https://www.google.com/maps/search/?api=1&query=Bellatrino+Pizzeria%2C+920+S+Harwood+St%2C+Farmers+Market%2C+Dallas%2C+TX", menu: "https://www.bellatrino.com/", tags: ["Neapolitan", "Farmers Market"] },
  { cat: 'pizza', name: "Pie Tap", rating: 4.6, count: 2714, price: 2, address: "1212 Oak Lawn Ave, Design District", note: "Pizza + rotisserie + bar combo. Twin-oven crust technique. Happy hour deal: 3 pizzas for ~$50. Dog-friendly patio.", maps: "https://www.google.com/maps/search/?api=1&query=Pie+Tap%2C+1212+Oak+Lawn+Ave%2C+Design+District%2C+Dallas%2C+TX", menu: "https://www.pietap.com/", tags: ["Happy hour", "Patio"] },
  { cat: 'pizza', name: "Stoner's Pizza Joint", rating: 4.8, count: 270, price: 2, address: "2325 N Fitzhugh Ave, Knox/Henderson", note: "Walking distance from your place. Open till 3am Fri/Sat — late-night pizza move. Hot Honey wings, Nice To Meat You pizza, Buffalo chicken stromboli are all fire. Small spot, mostly to-go.", maps: "https://www.google.com/maps/search/?api=1&query=Stoner%27s+Pizza+Joint%2C+2325+N+Fitzhugh+Ave%2C+Knox%2FHenderson%2C+Dallas%2C+TX", menu: "https://www.stonerspizzajoint.com/", tags: ["Walkable", "3am Fri-Sat", "Late night"] },

  // ===== ASIAN =====
  { cat: 'asian', name: "WAYA Japanese Izakaya", rating: 4.7, count: 1005, price: 2, address: "6334 Gaston Ave", note: "Tiny izakaya, big food. Wagyu sushi torched in front of you. Tonkotsu miso ramen is killer. Expect a wait — worth it.", maps: "https://www.google.com/maps/search/?api=1&query=WAYA+Japanese+Izakaya%2C+6334+Gaston+Ave%2C+Dallas%2C+TX", menu: "https://www.wayadallas.com/", tags: ["Wagyu", "Ramen"] },
  { cat: 'asian', name: "Wabi House", rating: 4.6, count: 2493, price: 2, address: "1802 Greenville Ave", note: "Greenville Ave ramen + cocktails. Spicy miso ramen + karaage are the move. Happy hour daily 3-7pm. Solid date or solo dinner.", maps: "https://www.google.com/maps/search/?api=1&query=Wabi+House%2C+1802+Greenville+Ave%2C+Dallas%2C+TX", menu: "https://www.wabihouse.com/", tags: ["Ramen", "Daily HH"] },
  { cat: 'asian', name: "Moriya Shokudo", rating: 4.7, count: 454, price: 2, address: "1920 N Coit Rd, Richardson", note: "Authentic Japanese comfort food. Spicy Jiro Ramen, katsu curry, takoyaki. Worth the drive to Richardson.", maps: "https://www.google.com/maps/search/?api=1&query=Moriya+Shokudo%2C+1920+N+Coit+Rd%2C+Richardson%2C+Dallas%2C+TX", menu: "https://moriyashokudo.com/", tags: ["Authentic", "Worth drive"] },
  { cat: 'asian', name: "Anchor Sushi Bar", rating: 4.8, count: 949, price: 3, address: "3130 Knox St, Knox", note: "Walking distance from your place. 4.8 stars, 950+ reviews. Upscale nautical vibe — sushi, sashimi, A5 wagyu dumplings. The chef's pressed roll is the move. Open till 11pm Fri/Sat. Dog-friendly patio.", maps: "https://www.google.com/maps/search/?api=1&query=Anchor+Sushi+Bar%2C+3130+Knox+St%2C+Knox%2C+Dallas%2C+TX", menu: "https://anchorsushibar.com/", tags: ["Walkable", "Knox", "Upscale"] },
  { cat: 'asian', name: "Namo", rating: 4.7, count: 612, price: 4, address: "3699 McKinney Ave, Uptown", note: "Uptown sushi spot — sit at the bar top, that's the move. Free parking in garage. Get the omakase or order off the menu. Closes 2:30-5pm — don't show up at 4pm. Closed Mondays.", maps: "https://www.google.com/maps/search/?api=1&query=Namo%2C+3699+McKinney+Ave%2C+Uptown%2C+Dallas%2C+TX", menu: "https://www.namodallas.com/", tags: ["Bar seating", "Omakase"] },
  { cat: 'asian', name: "Shoyo", rating: 4.8, count: 232, price: 4, address: "1916 Greenville Ave", note: "Top 5 omakase in Dallas. Intimate, ~12 seats. Chef Jimmy is a master. Reservations required, books out fast. Splurge — but worth it for special occasions.", maps: "https://www.google.com/maps/search/?api=1&query=Shoyo%2C+1916+Greenville+Ave%2C+Dallas%2C+TX", menu: "https://www.shoyodallas.com/", tags: ["Omakase", "Reservations"] },
  { cat: 'asian', name: "Sushi by Scratch", rating: 4.7, count: 123, price: 4, address: "1321 Commerce St, Inside The Adolphus Hotel", note: "Speakeasy-style omakase hidden inside The Adolphus Hotel. Pre-dinner welcome lounge, 17-course experience. Not cheap, but a real experience — anniversary or birthday spot.", maps: "https://www.google.com/maps/search/?api=1&query=Sushi+by+Scratch%2C+1321+Commerce+St%2C+Inside+The+Adolphus+Hotel%2C+Dallas%2C+TX", menu: "https://www.sushibyscratchrestaurants.com/dallas", tags: ["Speakeasy", "Special occasion"] },
  { cat: 'asian', name: "Sushiya", rating: 4.7, count: 935, price: 2, address: "1306 Elm St, Downtown", note: "Downtown gem. Way cheaper than the omakase spots — $$ instead of $$$$. Owner Terry treats you like family. Combo fried rice and Grace's Roll are favorites. Closed Sundays.", maps: "https://www.google.com/maps/search/?api=1&query=Sushiya%2C+1306+Elm+St%2C+Downtown%2C+Dallas%2C+TX", menu: "https://www.sushiyadallas.com/", tags: ["Affordable", "Downtown"] },

  // ===== MEXICAN =====
  { cat: 'mexican', name: "Velvet Taco", rating: 4.6, count: 2857, price: 2, address: "3411 McKinney Ave, Uptown", note: "Open till 3:30am Fri/Sat — best late-night taco move in Dallas. WTF Cordon Bleu is fan favorite. Sangria swirl rita pairs well.", maps: "https://www.google.com/maps/search/?api=1&query=Velvet+Taco%2C+3411+McKinney+Ave%2C+Uptown%2C+Dallas%2C+TX", menu: "https://www.velvettaco.com/", tags: ["Late night", "3am Fri-Sat"] },
  { cat: 'mexican', name: "Chilangos Tacos", rating: 4.6, count: 1471, price: 2, address: "4012 Ross Ave", note: "Feels like Mexico City. Carne asada, pastor, barbacoa, pollo all great. House-made tortillas + churros. Open till midnight Fri/Sat.", maps: "https://www.google.com/maps/search/?api=1&query=Chilangos+Tacos%2C+4012+Ross+Ave%2C+Dallas%2C+TX", menu: "https://chilangostacos.com/", tags: ["Authentic", "Late night"] },
  { cat: 'mexican', name: "Taquero", rating: 4.6, count: 703, price: 2, address: "5434 Ross Ave", note: "Mole enchiladas are the move. 3 house-made salsas with thick chips. Mango juice tastes like a mangonada. Cucumber margarita recommended.", maps: "https://www.google.com/maps/search/?api=1&query=Taquero%2C+5434+Ross+Ave%2C+Dallas%2C+TX", menu: "https://taquerodallas.com/", tags: ["Mole", "Solid margs"] },
  { cat: 'mexican', name: "Mi Cocina (Uptown)", rating: 4.7, count: 1129, price: 2, address: "3232 McKinney Ave, Uptown", note: "Tex-Mex classic. The Mambo Taxi margarita is famous in Dallas — order it. Brisket tacos and lemon drop margs are the move. Reliable, never misses.", maps: "https://www.google.com/maps/search/?api=1&query=Mi+Cocina+%28Uptown%29%2C+3232+McKinney+Ave%2C+Uptown%2C+Dallas%2C+TX", menu: "https://www.mcrowd.com/restaurants/mi-cocina/", tags: ["Mambo Taxi", "Tex-Mex"] },
  { cat: 'mexican', name: "Mesero (Inwood Village)", rating: 4.4, count: 684, price: 2, address: "5330 W Lovers Ln, Inwood Village", note: "Solid Mexican, beautiful decor. Ribeye is mid — go for the fish tacos or enchiladas instead. Avocado green sauce with chips is excellent. Margs are strong.", maps: "https://www.google.com/maps/search/?api=1&query=Mesero+%28Inwood+Village%29%2C+5330+W+Lovers+Ln%2C+Inwood+Village%2C+Dallas%2C+TX", menu: "https://www.meserorestaurants.com/", tags: ["Margs", "Inwood"] },

  // ===== AMERICAN =====
  { cat: 'american', name: "Knox Bistro", rating: 4.5, count: 907, price: 3, address: "3230 Knox St", note: "French bistro on Knox St. Walking distance from your place. Great brunch + dinner. Their foie gras is the play.", maps: "https://www.google.com/maps/search/?api=1&query=Knox+Bistro%2C+3230+Knox+St%2C+Dallas%2C+TX", menu: "https://knoxbistro.com/", tags: ["French", "Walkable"] },
  { cat: 'american', name: "The Hampton Social", rating: 4.8, count: 3623, price: 2, address: "1520 Main St, Downtown", note: "Coastal vibes downtown. Solid brunch spot. Tuna tartare + steak & eggs are the moves. Instagrammy if she's into that.", maps: "https://www.google.com/maps/search/?api=1&query=The+Hampton+Social%2C+1520+Main+St%2C+Downtown%2C+Dallas%2C+TX", menu: "https://www.thehamptonsocial.com/", tags: ["Brunch", "Coastal"] },
  { cat: 'american', name: "The Woolworth", rating: 4.8, count: 8540, price: 2, address: "1520 Elm St, Downtown", note: "4.8 stars over 8,500 reviews — that's rare. Solid cocktails + American food. Try the lobster mac.", maps: "https://www.google.com/maps/search/?api=1&query=The+Woolworth%2C+1520+Elm+St%2C+Downtown%2C+Dallas%2C+TX", menu: "https://www.thewoolworthdallas.com/", tags: ["Cocktails", "American"] },
  { cat: 'american', name: "LOCAL Public Eatery", rating: 4.9, count: 2590, price: 2, address: "2323 N Henderson Ave", note: "Henderson Ave. 4.9 stars. Brunch pizza is the move. Open till 1-2am — late-night hangover food too.", maps: "https://www.google.com/maps/search/?api=1&query=LOCAL+Public+Eatery%2C+2323+N+Henderson+Ave%2C+Dallas%2C+TX", menu: "https://localpubliceatery.com/neighbourhoods/henderson/", tags: ["Late night", "Brunch"] },
  { cat: 'american', name: "Green Point", rating: 4.8, count: 391, price: 2, address: "3219 Knox St", note: "Knox St oyster bar (but solid even if you skip seafood). Crab artichoke dip + good cocktails. Walking distance.", maps: "https://www.google.com/maps/search/?api=1&query=Green+Point%2C+3219+Knox+St%2C+Dallas%2C+TX", menu: "https://greenpointdallas.com/", tags: ["Knox St", "Cocktails"] },
  { cat: 'american', name: "Dragonfly", rating: 4.4, count: 687, price: 3, address: "Hotel ZaZa, 2332 Leonard St", note: "In Hotel ZaZa. Intimate, fancy, low-key. Lamb + ribeye are killer. The crème brûlée is a 'order it' move. Reservations.", maps: "https://www.google.com/maps/search/?api=1&query=Dragonfly%2C+Hotel+ZaZa%2C+2332+Leonard+St%2C+Dallas%2C+TX", menu: "https://www.hotelzaza.com/dallas/dining/dragonfly", tags: ["Hotel ZaZa", "Reservations"] },

  // ===== STEAKS / TASTING =====
  { cat: 'steaks', name: "Tango Room", rating: 4.6, count: 236, price: 4, address: "1617 Hi Line Dr", note: "Steakhouse, $$$$. Bone-in ribeye for two. For special-occasion only — anniversary, big milestones.", maps: "https://www.google.com/maps/search/?api=1&query=Tango+Room%2C+1617+Hi+Line+Dr%2C+Dallas%2C+TX", menu: "http://tangoroomdallas.com/", tags: ["Steakhouse", "Big splurge"] },
  { cat: 'steaks', name: "Quarter Acre", rating: 4.7, count: 236, price: 2, address: "2023 Greenville Ave", note: "7-course tasting menu, future Michelin energy. Reservations a must. For when you want to go all out.", maps: "https://www.google.com/maps/search/?api=1&query=Quarter+Acre%2C+2023+Greenville+Ave%2C+Dallas%2C+TX", menu: "http://www.quarteracrerestaurant.com/", tags: ["Tasting menu", "Greenville"] },
  { cat: 'steaks', name: "Gemma", rating: 4.7, count: 792, price: 2, address: "2323 N Henderson Ave", note: "Henderson Ave bistro. The warm raisin scones at start are legendary. Reservations required. One of the best dinners in town.", maps: "https://www.google.com/maps/search/?api=1&query=Gemma%2C+2323+N+Henderson+Ave%2C+Dallas%2C+TX", menu: "https://www.gemmadallas.com/", tags: ["Henderson", "Reservations"] },
  { cat: 'steaks', name: "Nick & Sam's", rating: 4.3, count: 4133, price: 4, address: "3008 Maple Ave, Uptown", note: "Dallas steakhouse classic. Famous free caviar bar before dinner. They walk a tray of raw cuts to your table. Make a reservation way in advance. Book a corner booth.", maps: "https://www.google.com/maps/search/?api=1&query=Nick+%26+Sam%27s%2C+3008+Maple+Ave%2C+Uptown%2C+Dallas%2C+TX", menu: "https://nick-sams.com/", tags: ["Caviar bar", "Reservations"] },
  { cat: 'steaks', name: "Bob's Steak & Chop House", rating: 4.6, count: 1339, price: 4, address: "4300 Lemmon Ave", note: "The signature glazed carrot is iconic. Bread service is amazing. Mashed potatoes are heavy on the garlic — you'll love it or hate it. Closed Sundays.", maps: "https://www.google.com/maps/search/?api=1&query=Bob%27s+Steak+%26+Chop+House%2C+4300+Lemmon+Ave%2C+Dallas%2C+TX", menu: "https://www.bobs-steakandchop.com/dallas/", tags: ["Iconic carrot", "Closed Sundays"] },

  // ===== BBQ =====
  { cat: 'bbq', name: "Cattleack BBQ", rating: 4.6, count: 2118, price: 2, address: "13628 Gamma Rd, Farmers Branch", note: "Texas Monthly Top 50. Wagyu burnt ends + giant pastrami ribs are the specialty. Open Wed-Fri only, 10am-2pm. Get there 15 min before opening or wait an hour. Worth the drive.", maps: "https://www.google.com/maps/search/?api=1&query=Cattleack+BBQ%2C+13628+Gamma+Rd%2C+Farmers+Branch%2C+Dallas%2C+TX", menu: "https://www.cattleackbbq.com/", tags: ["Wagyu burnt ends", "Wed-Fri only"] },
  { cat: 'bbq', name: "Terry Black's Barbecue", rating: 4.7, count: 12839, price: 2, address: "3025 Main St, Deep Ellum", note: "12,800+ reviews and still 4.7 — the real deal. Brisket, beef ribs, jalapeño cheddar sausage. Order at counter.", maps: "https://www.google.com/maps/search/?api=1&query=Terry+Black%27s+Barbecue%2C+3025+Main+St%2C+Deep+Ellum%2C+Dallas%2C+TX", menu: "https://terryblacksbbq.com/", tags: ["Deep Ellum", "Legendary"] },
  { cat: 'bbq', name: "Hurtado Barbecue", rating: 4.7, count: 843, price: 2, address: "900 S Harwood St, Downtown", note: "Texas BBQ × Mexican fusion. The birria taco is a $6 must-order. Hatch chile mac and cheese is next-level.", maps: "https://www.google.com/maps/search/?api=1&query=Hurtado+Barbecue%2C+900+S+Harwood+St%2C+Downtown%2C+Dallas%2C+TX", menu: "https://hurtadobarbecue.com/", tags: ["Tex-Mex BBQ", "Birria taco"] },
  { cat: 'bbq', name: "Oak'd BBQ", rating: 4.4, count: 2158, price: 2, address: "5500 Greenville Ave", note: "Greenville Ave BBQ + sports bar. Wagyu brisket is the headline. Texas Twinkie + 4-meat plate combo. Free samples.", maps: "https://www.google.com/maps/search/?api=1&query=Oak%27d+BBQ%2C+5500+Greenville+Ave%2C+Dallas%2C+TX", menu: "https://oakdbbq.com/", tags: ["Wagyu", "Greenville"] },
  { cat: 'bbq', name: "Hutchins BBQ (Trophy Club)", rating: 4.8, count: 3559, price: 2, address: "3000 TX-114, Trophy Club", note: "30 min north but worth the drive. 4.8 over 3,500 reviews. Family pack feeds 6. Brisket + mac & cheese + cobbler combo.", maps: "https://www.google.com/maps/search/?api=1&query=Hutchins+BBQ+%28Trophy+Club%29%2C+3000+TX-114%2C+Trophy+Club%2C+Dallas%2C+TX", menu: "https://hutchinsbbq.com/", tags: ["Worth drive", "Family pack"] },

  // ===== HEALTHY =====
  { cat: 'healthy', name: "Eatzi's Market & Bakery", rating: 4.5, count: 3647, price: 2, address: "3403 Oak Lawn Ave", note: "Fresh sandwiches under $10, salmon burger, breakfast burritos, salad bar, prepared meals to-go. Best 'real food fast' option in Dallas.", maps: "https://www.google.com/maps/search/?api=1&query=Eatzi%27s+Market+%26+Bakery%2C+3403+Oak+Lawn+Ave%2C+Dallas%2C+TX", menu: "https://eatzis.com/", tags: ["YOUR PICK", "Best sandwiches"], fav: true },
  { cat: 'healthy', name: "True Food Kitchen", rating: 4.4, count: 1552, price: 2, address: "8383 Preston Center Plaza", note: "Healthy menu by Dr. Andrew Weil — anti-inflammatory focus. Edamame dumplings + butternut squash spaghetti are standouts. Solid clean-eating dinner spot.", maps: "https://www.google.com/maps/search/?api=1&query=True+Food+Kitchen%2C+8383+Preston+Center+Plaza%2C+Dallas%2C+TX", menu: "https://www.truefoodkitchen.com/", tags: ["Anti-inflammatory", "Clean dinner"] },
  { cat: 'healthy', name: "Flower Child", rating: 4.5, count: 1225, price: 2, address: "5450 W Lovers Ln", note: "Bowls, kabobs, salads. Mother Earth bowl is the signature. Vegetarian-leaning but plenty of protein options. Right by Mr. Winston's.", maps: "https://www.google.com/maps/search/?api=1&query=Flower+Child%2C+5450+W+Lovers+Ln%2C+Dallas%2C+TX", menu: "https://www.iamaflowerchild.com/", tags: ["Bowls", "Bright space"] },
  { cat: 'healthy', name: "Original ChopShop", rating: 4.6, count: 688, price: 2, address: "6401 Hillcrest Ave", note: "Bowls, salads, breakfast burritos, smoothies. Open 7am-9pm. Hot Honey Chicken Bowl + New Salsa Bowl are the moves. Fast casual done right.", maps: "https://www.google.com/maps/search/?api=1&query=Original+ChopShop%2C+6401+Hillcrest+Ave%2C+Dallas%2C+TX", menu: "https://www.originalchopshop.com/", tags: ["Bowls", "All-day"] },
  { cat: 'healthy', name: "Crisp & Green", rating: 4.6, count: 292, price: 2, address: "6333 E Mockingbird Ln, Mockingbird Station", note: "Salad-focused. Soule Bowl and Bombastic Bowl are favorites. Acai bowls solid too. Sign up for the app for reward points. Open till 9pm every day.", maps: "https://www.google.com/maps/search/?api=1&query=Crisp+%26+Green%2C+6333+E+Mockingbird+Ln%2C+Mockingbird+Station%2C+Dallas%2C+TX", menu: "https://www.crispandgreen.com/", tags: ["Salad bowls", "Acai"] },

  // ===== FAST FOOD =====
  { cat: 'fastfood', name: "Chick-fil-A", rating: 4.1, count: 4316, price: 1, address: "3040 W Mockingbird Ln", note: "You know the move. Open 6am-12am, closed Sundays. Closest standalone CFA to you. Order ahead, skip the line.", maps: "https://www.google.com/maps/search/?api=1&query=Chick-fil-A%2C+3040+W+Mockingbird+Ln%2C+Dallas%2C+TX", menu: "https://www.chick-fil-a.com/menu", tags: ["Closed Sun", "Open till 12"] },
  { cat: 'fastfood', name: "In-N-Out Burger", rating: 4.4, count: 6119, price: 1, address: "7940 N Central Expy", note: "Animal-style fries, Double-Double, secret menu. Open till 1am most nights. Line is always long but moves fast.", maps: "https://www.google.com/maps/search/?api=1&query=In-N-Out+Burger%2C+7940+N+Central+Expy%2C+Dallas%2C+TX", menu: "https://www.in-n-out.com/menu", tags: ["Late night", "Cheap"] },
  { cat: 'fastfood', name: "Five Guys", rating: 4.0, count: 581, price: 2, address: "13350 Dallas Pkwy (Galleria)", note: "Galleria Mall. Pricey for fast food but the Cajun fries + free peanuts setup is iconic. Bring a buddy for the giant fry portion.", maps: "https://www.google.com/maps/search/?api=1&query=Five+Guys%2C+13350+Dallas+Pkwy+%28Galleria%29%2C+Dallas%2C+TX", menu: "https://www.fiveguys.com/menu", tags: ["Pricey", "Cajun fries"] },
  { cat: 'fastfood', name: "Chipotle (Knox/McKinney)", rating: 3.8, count: 668, price: 1, address: "4502 McKinney Ave", note: "Closest Chipotle to you. Open till 11pm daily. Bowl with double chicken + guac is the formula. Park-finding can suck.", maps: "https://www.google.com/maps/search/?api=1&query=Chipotle+%28Knox%2FMcKinney%29%2C+4502+McKinney+Ave%2C+Dallas%2C+TX", menu: "https://www.chipotle.com/menu", tags: ["Walkable", "Late hours"] },
  { cat: 'fastfood', name: "Taco Bell (Greenville)", rating: 3.5, count: 858, price: 1, address: "7110 Greenville Ave", note: "Open till 4am every night. Drunk-food endgame. Go for the nacho fries when they're back.", maps: "https://www.google.com/maps/search/?api=1&query=Taco+Bell+%28Greenville%29%2C+7110+Greenville+Ave%2C+Dallas%2C+TX", menu: "https://www.tacobell.com/food", tags: ["4am close", "Drunk food"] },
  { cat: 'fastfood', name: "Popeyes", rating: 3.2, count: 889, price: 1, address: "Multiple Dallas locations", note: "The chicken sandwich speaks for itself. Most Dallas locations open till 11pm. Search the closest one when craving hits.", maps: "https://www.google.com/maps/search/?api=1&query=Popeyes%2C+Multiple+Dallas+locations%2C+Dallas%2C+TX", menu: "https://www.popeyes.com/menu", tags: ["Sandwich GOAT", "Multiple locs"] },

  // ===== COFFEE =====
  { cat: 'coffee', name: "Buzz & Bustle", rating: 4.3, count: 338, price: 1, address: "5610 Village Glen Dr, The Village", note: "Your favorite. Coffee shop + bodega in one. Modern, relaxed, perfect for working or eating. 7am-7pm daily.", maps: "https://www.google.com/maps/search/?api=1&query=Buzz+%26+Bustle%2C+5610+Village+Glen+Dr%2C+The+Village%2C+Dallas%2C+TX", menu: "https://buzzandbustle.com/", tags: ["FAVORITE", "Bodega"], fav: true },
  { cat: 'coffee', name: "Westside Coffee", rating: 4.9, count: 98, price: 2, address: "4711 Westside Dr", note: "Inside a converted church, super spacious. 7am opens. Free parking. Best for working remotely. Sundays closed.", maps: "https://www.google.com/maps/search/?api=1&query=Westside+Coffee%2C+4711+Westside+Dr%2C+Dallas%2C+TX", menu: "http://www.orderwestsidecoffee.com/", tags: ["Work-friendly", "Spacious"] },
  { cat: 'coffee', name: "JuJu's Coffee", rating: 4.9, count: 208, price: 2, address: "6038 La Vista Dr", note: "Local hidden gem near Lakewood. Real coffee nerds, no syrup-bombs. Closed Tuesdays. East Dallas Blend is signature.", maps: "https://www.google.com/maps/search/?api=1&query=JuJu%27s+Coffee%2C+6038+La+Vista+Dr%2C+Dallas%2C+TX", menu: "http://jujuscoffee.com/", tags: ["Specialty", "Hidden gem"] },
  { cat: 'coffee', name: "Fairgrounds Coffee", rating: 4.4, count: 276, price: 2, address: "4514 Cole Ave", note: "Knox/Henderson, walking distance from you. Rope swings inside (yes, really). Tahini espresso is wild. Open till 6pm.", maps: "https://www.google.com/maps/search/?api=1&query=Fairgrounds+Coffee%2C+4514+Cole+Ave%2C+Dallas%2C+TX", menu: "https://www.fairgrounds.cafe/cafe-dallas/", tags: ["Walkable", "Quirky"] },
  { cat: 'coffee', name: "Sip Stir Coffee", rating: 4.4, count: 676, price: 2, address: "3800 McKinney Ave, Uptown", note: "McKinney Ave Uptown. Spacious, quiet, made for laptop work. Try the Gulab Jamun latte (now permanent).", maps: "https://www.google.com/maps/search/?api=1&query=Sip+Stir+Coffee%2C+3800+McKinney+Ave%2C+Uptown%2C+Dallas%2C+TX", menu: "http://sipstircoffeehouse.com/", tags: ["Uptown", "Work-friendly"] },
  { cat: 'coffee', name: "Wayward Coffee", rating: 4.5, count: 345, price: 2, address: "2025 E Irving Blvd", note: "Huge space, tons of seating, even meeting rooms. 7am-7pm every day. Best for serious work sessions.", maps: "https://www.google.com/maps/search/?api=1&query=Wayward+Coffee%2C+2025+E+Irving+Blvd%2C+Dallas%2C+TX", menu: "http://waywardcoffee.co/", tags: ["Late hours", "Big space"] },
  { cat: 'coffee', name: "Merit Coffee", rating: 4.3, count: 277, price: 2, address: "4228 Oak Lawn Ave", note: "Oak Lawn. Mini-chain with serious beans. Service can be slow, coffee makes up for it.", maps: "https://www.google.com/maps/search/?api=1&query=Merit+Coffee%2C+4228+Oak+Lawn+Ave%2C+Dallas%2C+TX", menu: "https://meritcoffee.com/", tags: ["Late hours", "Whole bean"] },
  { cat: 'coffee', name: "Ascension Coffee", rating: 4.4, count: 2529, price: 2, address: "1621 Oak Lawn Ave, Design District", note: "Cafe + wine bar combo. Floor-to-ceiling glass, modern. Free valet. Solid food menu for lunch meetings.", maps: "https://www.google.com/maps/search/?api=1&query=Ascension+Coffee%2C+1621+Oak+Lawn+Ave%2C+Design+District%2C+Dallas%2C+TX", menu: "https://www.ascensiondallas.com/", tags: ["Design District", "Wine bar"] },
  { cat: 'coffee', name: "Starbucks (Knox)", rating: 4.1, count: 485, price: 2, address: "3216 Knox St", note: "Your nearby Starbucks. 4:30am-9pm daily — useful when nothing else is open.", maps: "https://www.google.com/maps/search/?api=1&query=Starbucks+%28Knox%29%2C+3216+Knox+St%2C+Dallas%2C+TX", menu: "https://www.starbucks.com/menu", tags: ["Walkable", "Always open"] },

  // ===== NIGHTLIFE =====
  { cat: 'nightlife', name: "It'll Do Club", rating: 4.3, count: 721, price: 2, address: "4322 Elm St, Deep Ellum", note: "Cult-favorite Deep Ellum club. Sunday's 'The Church' is the legendary night. Music-first, no Vegas-bottle-service vibes. Uber it.", maps: "https://www.google.com/maps/search/?api=1&query=It%27ll+Do+Club%2C+4322+Elm+St%2C+Deep+Ellum%2C+Dallas%2C+TX", tags: ["Deep Ellum", "Sunday vibes"] },
  { cat: 'nightlife', name: "Green Light Social", rating: 3.8, count: 538, price: 2, address: "2625 Floyd St, Uptown", note: "3-in-1 venue: arcade bar, club, rooftop lounge. Free entry, mid-20s crowd. Best gateway club for going out in Uptown.", maps: "https://www.google.com/maps/search/?api=1&query=Green+Light+Social%2C+2625+Floyd+St%2C+Uptown%2C+Dallas%2C+TX", tags: ["Uptown", "Free entry"] },
  { cat: 'nightlife', name: "The Tipsy Alchemist", rating: 4.4, count: 968, price: 3, address: "2101 Cedar Springs Rd", note: "Lounge that turns into a club after 10pm. Solid craft cocktails, Uptown crowd. Reserve a spot if you want to actually sit.", maps: "https://www.google.com/maps/search/?api=1&query=The+Tipsy+Alchemist%2C+2101+Cedar+Springs+Rd%2C+Dallas%2C+TX", tags: ["Cocktails", "Lounge"] },
  { cat: 'nightlife', name: "Rokwood", rating: 4.4, count: 212, price: 2, address: "600 Jackson St, Downtown", note: "Upscale ultraclub, Friday/Saturday only. Drink specials before midnight. Bring the energy if you go.", maps: "https://www.google.com/maps/search/?api=1&query=Rokwood%2C+600+Jackson+St%2C+Downtown%2C+Dallas%2C+TX", tags: ["Weekends only", "Upscale"] },
  { cat: 'nightlife', name: "The Nines", rating: 4.0, count: 266, price: 2, address: "2911 Main St, Deep Ellum", note: "Deep Ellum hip-hop club. THC-infused cocktails. Big upstairs dance floor. For a real club night.", maps: "https://www.google.com/maps/search/?api=1&query=The+Nines%2C+2911+Main+St%2C+Deep+Ellum%2C+Dallas%2C+TX", tags: ["Hip-hop", "Late night"] },
  { cat: 'nightlife', name: "Taboo Lounge", rating: 4.2, count: 540, price: 2, address: "1418 N Riverfront Blvd", note: "Hookah + lounge + sports bar. $1 taco Tuesdays, $2 draft Friday happy hour. Cheap night out option.", maps: "https://www.google.com/maps/search/?api=1&query=Taboo+Lounge%2C+1418+N+Riverfront+Blvd%2C+Dallas%2C+TX", tags: ["Hookah", "Cheap"] },
  { cat: 'nightlife', name: "Cowboys Red River", rating: 4.5, count: 4991, price: 2, address: "10310 Technology Blvd W", note: "Texas dancehall + saloon. Live country music, two-stepping, free Wednesday dance class. Pure Footloose energy. Wed–Sat only.", maps: "https://www.google.com/maps/search/?api=1&query=Cowboys+Red+River%2C+10310+Technology+Blvd+W%2C+Dallas%2C+TX", tags: ["Country", "Dancehall"] },

  // ===== GYM =====
  { cat: 'gym', name: "Dallas JCC", rating: 4.7, count: 687, price: 2, address: "7900 Northaven Rd", note: "Aaron Family JCC. Indoor + outdoor pool, basketball, gymnastics, sauna, full gym. Recently renovated. Full community fit.", maps: "https://www.google.com/maps/search/?api=1&query=Dallas+JCC%2C+7900+Northaven+Rd%2C+Dallas%2C+TX", menu: "https://www.jccdallas.org/", tags: ["Pool", "Community"] },
  { cat: 'gym', name: "PARADIGM Gym 24hr", rating: 5.0, count: 24, price: 3, address: "4140 Lemmon Ave, Uptown", note: "24/7, Uptown. Rogue/Arsenal equipment. Sauna, kettlebells up to 123lbs. Best premium gym for serious lifting.", maps: "https://www.google.com/maps/search/?api=1&query=PARADIGM+Gym+24hr%2C+4140+Lemmon+Ave%2C+Uptown%2C+Dallas%2C+TX", menu: "https://www.paradigmgyms.com/", tags: ["24/7", "Premium"] },
  { cat: 'gym', name: "Trophy Fitness Uptown", rating: 4.8, count: 153, price: 2, address: "2812 Vine St, Uptown", note: "Multi-location membership, free towel, sauna, cold plunge. Mid-priced. Friendly. Great for bro-split lifting.", maps: "https://www.google.com/maps/search/?api=1&query=Trophy+Fitness+Uptown%2C+2812+Vine+St%2C+Uptown%2C+Dallas%2C+TX", menu: "https://trophyfitness.com/dallas-uptown/", tags: ["Sauna", "Mid-priced"] },
  { cat: 'gym', name: "Training Mate Highland Park", rating: 4.9, count: 152, price: 3, address: "3858 Oak Lawn Ave #430, Highland Park", note: "Walking distance from your place. Group HIIT classes, 50-min sessions. Kaitlyn and Mackenzie are the trainers people rave about. Music-driven, high energy. Drop-in or membership.", maps: "https://www.google.com/maps/search/?api=1&query=Training+Mate+Highland+Park%2C+3858+Oak+Lawn+Ave+%23430%2C+Highland+Park%2C+Dallas%2C+TX", menu: "https://www.trainingmate.com/highland-park/", tags: ["Walkable", "HIIT", "Highland Park"] },
  { cat: 'gym', name: "The Exercise Coach (Lovers Lane)", rating: 4.8, count: 49, price: 3, address: "5600 W Lovers Ln #219", note: "20-minute strength sessions, 2x/week. Sounds like nothing but it works — strength training with custom resistance machines. Good if you're time-poor. Closed Sundays.", maps: "https://www.google.com/maps/search/?api=1&query=The+Exercise+Coach+%28Lovers+Lane%29%2C+5600+W+Lovers+Ln+%23219%2C+Dallas%2C+TX", menu: "https://www.exercisecoach.com/locations/highland-park/", tags: ["20-min sessions", "Strength"] },

  // ===== BARBER =====
  { cat: 'barber', name: "Mr. Winston's", rating: 5.0, count: 68, price: 2, address: "5600 W Lovers Ln, Floor 2", note: "Where you cut your hair. 5.0 stars. David, Brittany Nicole, Jessica all get rave reviews. Beer + liquor available during cuts. Closed Sundays.", maps: "https://www.google.com/maps/search/?api=1&query=Mr.+Winston%27s%2C+5600+W+Lovers+Ln%2C+Floor+2%2C+Dallas%2C+TX", menu: "https://www.mrwinstonsdallas.com/", tags: ["YOUR SPOT", "5.0 stars"], fav: true },
  { cat: 'barber', name: "Scissors & Scotch", rating: 4.9, count: 2046, price: 3, address: "100 Crescent Ct, Uptown", note: "Crescent Court, upscale. Membership model with free drinks. Pricey ($60+) but full experience. KC and Kryz are top.", maps: "https://www.google.com/maps/search/?api=1&query=Scissors+%26+Scotch%2C+100+Crescent+Ct%2C+Uptown%2C+Dallas%2C+TX", menu: "https://scissorsscotch.com/locations/tx/dallas/uptown/", tags: ["Upscale", "Membership"] },
  { cat: 'barber', name: "HQ Barbershop", rating: 5.0, count: 321, price: 2, address: "3527 Oak Lawn Ave", note: "5.0 stars. Ask for Jordan — best skin fade in Dallas, people drive from Houston. Anwar is the man for shaves and beard trims. Open till 9pm weekdays. Sundays open till 5pm.", maps: "https://www.google.com/maps/search/?api=1&query=HQ+Barbershop%2C+3527+Oak+Lawn+Ave%2C+Dallas%2C+TX", menu: "https://hqbarbershopdallas.com/", tags: ["5.0 stars", "Best fade"] },
  { cat: 'barber', name: "Exclusive Men's Grooming", rating: 4.9, count: 936, price: 2, address: "17630 Davenport Rd #106, North Dallas", note: "Drive up north for this one. Full-service grooming spa — beard trims, waxing, facials. Ask for Rafael Ramos. Open till 8:30pm. Worth the trip if you want the spa experience.", maps: "https://www.google.com/maps/search/?api=1&query=Exclusive+Men%27s+Grooming%2C+17630+Davenport+Rd+%23106%2C+North+Dallas%2C+Dallas%2C+TX", menu: "https://exclusivemensgrooming.com/", tags: ["Spa experience", "North Dallas"] },

  // ===== GROCERY =====
  { cat: 'grocery', name: "Trader Joe's", rating: 4.7, count: 1382, price: 2, address: "4525 Cole Ave, Knox/Henderson", note: "Your go-to. 5 min from you. Limited but curated.", maps: "https://www.google.com/maps/search/?api=1&query=Trader+Joe%27s%2C+4525+Cole+Ave%2C+Knox%2FHenderson%2C+Dallas%2C+TX", specialty: "BEST FOR: Frozen meals, snacks, cheap wine, sourdough bread, everything bagel seasoning, kung pao chicken, dark chocolate, dumplings, prepared salads. SKIP: Specialty cheeses, fresh fish, gourmet ingredients, big brand-names.", tags: ["5 min away", "Frozen + snacks"] },
  { cat: 'grocery', name: "Central Market", rating: 4.6, count: 4207, price: 1, address: "5750 E Lovers Ln", note: "Massive gourmet store. Slightly further but worth it.", maps: "https://www.google.com/maps/search/?api=1&query=Central+Market%2C+5750+E+Lovers+Ln%2C+Dallas%2C+TX", specialty: "BEST FOR: Specialty cheeses, fresh produce, prepared meals, butcher cuts, hard-to-find ingredients, international foods, fresh-baked bread, custom sandwiches, wine. THE PLAY: When you need anything gourmet — start here.", tags: ["Gourmet", "Best produce"] },
  { cat: 'grocery', name: "Tom Thumb (Snider Plaza)", rating: 4.3, count: 267, price: 2, address: "7000 Snider Plaza", note: "Standard American grocery. Open until 11pm.", maps: "https://www.google.com/maps/search/?api=1&query=Tom+Thumb+%28Snider+Plaza%29%2C+7000+Snider+Plaza%2C+Dallas%2C+TX", specialty: "BEST FOR: Late-night runs (open till 11pm), brand-name groceries, household basics, lamb cuts, soda variety. SKIP: Premium produce, gourmet stuff. THE PLAY: When TJ's is closed or you need a specific big-brand item.", tags: ["11pm close", "Brand names"] },
  { cat: 'grocery', name: "K Market Kosher Grocery & Deli", rating: 4.8, count: 181, price: 2, address: "6911 Frankford Rd #600, North Dallas", note: "Best kosher market in Dallas. Full deli, kosher meat, Shabbat catering, pantry staples. Open Sun-Thu till 6pm, Friday till 4pm, closed Saturdays. Worth the drive for Shabbat dinner.", maps: "https://www.google.com/maps/search/?api=1&query=K+Market+Kosher+Grocery+%26+Deli%2C+6911+Frankford+Rd+%23600%2C+North+Dallas%2C+Dallas%2C+TX", menu: "https://kmarketdallas.com/", tags: ["Kosher", "Shabbat catering", "North Dallas"] },

  // ===== WELLNESS =====
  { cat: 'wellness', name: "Riviera Spa - Knox", rating: 4.7, count: 691, price: 3, address: "4514 Travis St, Knox/Henderson", note: "Walking distance from your place. Massages, lymphatic drainage, sauna. Complimentary champagne in the lobby. Ask for Willow or Nya. Open till 9pm.", maps: "https://www.google.com/maps/search/?api=1&query=Riviera+Spa+-+Knox%2C+4514+Travis+St%2C+Knox%2FHenderson%2C+Dallas%2C+TX", menu: "https://rivieraspa.com/", tags: ["Walkable", "Knox", "Massages"] },
  { cat: 'wellness', name: "GreenLotus Spa", rating: 4.8, count: 1403, price: 2, address: "4447 N Central Expy", note: "1,400+ reviews. Massage + facial combos, lymphatic massage, hot stones, CBD options. Open till 9:30pm every day. Heads up: they push upgrades.", maps: "https://www.google.com/maps/search/?api=1&query=GreenLotus+Spa%2C+4447+N+Central+Expy%2C+Dallas%2C+TX", menu: "https://greenlotusspadallas.com/", tags: ["Late hours", "Combo deals"] },
  { cat: 'wellness', name: "Zelene Head Spa", rating: 5.0, count: 767, price: 3, address: "2935 Blackburn St, West Village", note: "5.0 stars. Japanese head spa — scalp analysis + scalp + neck/shoulder massage. Trendy, leaves your hair clean. Combo with facial is the move.", maps: "https://www.google.com/maps/search/?api=1&query=Zelene+Head+Spa%2C+2935+Blackburn+St%2C+West+Village%2C+Dallas%2C+TX", menu: "https://www.zelenespa.com/", tags: ["Head spa", "Trendy"] },
  { cat: 'wellness', name: "Manos Nail Bar", rating: 4.9, count: 716, price: 2, address: "4009 Lemmon Ave, Uptown", note: "Best-rated nail salon in Uptown. 20% off Mon-Thu until 3pm. No appointment needed. Ask for Patrick or Jenni for Gel-X. Open till 8pm.", maps: "https://www.google.com/maps/search/?api=1&query=Manos+Nail+Bar%2C+4009+Lemmon+Ave%2C+Uptown%2C+Dallas%2C+TX", menu: "https://manosnailbar.com/", tags: ["Walk-in OK", "Mon-Thu deal"] },
  { cat: 'wellness', name: "Vogue Nail Bar", rating: 4.8, count: 469, price: 2, address: "5706 E Mockingbird Ln", note: "Mockingbird Station. Hot Date pedicure is amazing. Massive color selection, builder gel + 3D nail art. Ask for Ruby (designs) or Linh (detail). Open till 7:30pm.", maps: "https://www.google.com/maps/search/?api=1&query=Vogue+Nail+Bar%2C+5706+E+Mockingbird+Ln%2C+Dallas%2C+TX", menu: "https://www.voguenailbar.com/", tags: ["Nail art", "Pedicures"] },

  // ===== HEALTHCARE =====
  { cat: 'healthcare', name: "Highland Park ER", rating: 4.6, count: 1069, price: 4, address: "5150 Lemmon Ave, Highland Park", note: "Open 24/7. Standalone ER, way faster than hospital ERs for non-life-threatening stuff (broken bones, cuts, fevers). Cleaner, calmer, less wait. Save in your phone.", maps: "https://www.google.com/maps/search/?api=1&query=Highland+Park+ER%2C+5150+Lemmon+Ave%2C+Highland+Park%2C+Dallas%2C+TX", menu: "https://highlandparker.com/", tags: ["24/7", "Save in phone"] },
  { cat: 'healthcare', name: "Highland Park Dental", rating: 4.9, count: 578, price: 3, address: "6725 Hillcrest Ave", note: "4.9 stars. Cleanings, cosmetic work, wisdom teeth. Open till 7pm Mondays for after-work appts. Free coffee in the waiting room. Closed weekends.", maps: "https://www.google.com/maps/search/?api=1&query=Highland+Park+Dental%2C+6725+Hillcrest+Ave%2C+Dallas%2C+TX", menu: "https://highlandparkdentaldfw.com/", tags: ["Cleanings", "After-work appts"] },
  { cat: 'healthcare', name: "Revive Primary Care", rating: 4.9, count: 227, price: 2, address: "3330 Douglas Ave, Highland Park", note: "Primary care + med spa combo. 4.9 stars. Annual checkups, blood work, prescriptions. Saturday hours till 2pm. Good for routine doctor stuff.", maps: "https://www.google.com/maps/search/?api=1&query=Revive+Primary+Care%2C+3330+Douglas+Ave%2C+Highland+Park%2C+Dallas%2C+TX", menu: "https://reviveprimarycare.com/", tags: ["Saturday hours", "Annual checkup"] },
  { cat: 'healthcare', name: "CVS Pharmacy (Preston)", rating: 3.3, count: 47, price: 2, address: "6709 Preston Rd", note: "Closest CVS for prescriptions. 7am-11pm weekdays. Reviews are mid but it's close and convenient — fine for refills, OTC stuff, last-minute basics.", maps: "https://www.google.com/maps/search/?api=1&query=CVS+Pharmacy+%28Preston%29%2C+6709+Preston+Rd%2C+Dallas%2C+TX", menu: "https://www.cvs.com/", tags: ["Pharmacy", "Late hours"] },

  // ===== ACTIVITIES =====
  { cat: 'activities', name: "TopGolf Dallas", rating: 4.4, count: 3422, price: 2, address: "8787 Park Ln, North Dallas", note: "Classic group activity. Reserve a bay online — walk-ins wait forever on weekends. Mini golf is also $9/person if golf isn't your thing. Open till 1am every night. Get there early or book ahead.", maps: "https://www.google.com/maps/search/?api=1&query=TopGolf+Dallas%2C+8787+Park+Ln%2C+North+Dallas", tags: ["Reserve online", "Group activity", "Mini golf"] },
  { cat: 'activities', name: "BowlGames", rating: 4.7, count: 324, price: 2, address: "139 Turtle Creek Blvd Suite 120, Design District", note: "Adult-style bowling spot. Snooker, darts, foosball too. Weekday 4-10pm, weekends 11am till late. Closed Mondays. Book ahead for groups. Lemon pepper wings are solid, drinks are limited.", maps: "https://www.google.com/maps/search/?api=1&query=BowlGames%2C+139+Turtle+Creek+Blvd+Suite+120%2C+Design+District", tags: ["Bowling", "Group spot", "Closed Mondays"] },
  { cat: 'activities', name: "Escapology Victory Park", rating: 4.9, count: 2561, price: 2, address: "2375 Victory Park Ln Suite 110, Victory Park", note: "4.9 stars. Best escape rooms in Dallas — 7 Deadly Sins and Budapest Express are favorites. Allow 1 hr per room. Group of 4-8 is ideal. Book online, weekends fill up.", maps: "https://www.google.com/maps/search/?api=1&query=Escapology+Victory+Park%2C+2375+Victory+Park+Ln+Suite+110%2C+Victory+Park", tags: ["Escape rooms", "Date night", "Groups"] },
  { cat: 'activities', name: "Dallas Museum of Art", rating: 4.7, count: 12782, price: 1, address: "1717 N Harwood St, Arts District", note: "FREE general admission. 4 floors, 12k+ reviews. Closed Mon-Tue, open Wed-Sun 11am-5pm. Free bag check. Plan 2 hrs minimum. Special exhibits cost extra.", maps: "https://www.google.com/maps/search/?api=1&query=Dallas+Museum+of+Art%2C+1717+N+Harwood+St%2C+Arts+District", tags: ["Free entry", "Closed Mon-Tue", "Arts District"] },
  { cat: 'activities', name: "Nasher Sculpture Center", rating: 4.6, count: 1754, price: 2, address: "2001 Flora St, Arts District", note: "Outdoor sculpture garden is the highlight. 'Til Midnight at the Nasher' (warm months) is a vibe — music, art, drinks under the stars. Closed Mon-Tue. Smaller than DMA, plan ~1.5hrs.", maps: "https://www.google.com/maps/search/?api=1&query=Nasher+Sculpture+Center%2C+2001+Flora+St%2C+Arts+District", tags: ["Sculpture garden", "Date worthy", "Arts District"] },
  { cat: 'activities', name: "Klyde Warren Park", rating: 4.7, count: 18684, price: 1, address: "2012 Woodall Rodgers Fwy, Downtown", note: "FREE. 5-acre park built over a freeway. Food trucks daily, live music weekends, kids splash pad. 5 min walk to DMA + Nasher = perfect culture day combo. Parking is annoying — Uber recommended.", maps: "https://www.google.com/maps/search/?api=1&query=Klyde+Warren+Park%2C+2012+Woodall+Rodgers+Fwy%2C+Downtown", tags: ["Free", "Food trucks", "Family-friendly"] },
  { cat: 'activities', name: "Katy Trail", rating: 4.8, count: 500, price: 1, address: "3505 N Hall St, Knox/Henderson", note: "Walking distance from your place. 3.5-mile paved trail through Uptown. Walk, run, bike, dog walk. Connects Knox to Victory Park. Best at golden hour. Get on at the Knox-Henderson entrance.", maps: "https://www.google.com/maps/search/?api=1&query=Katy+Trail%2C+3505+N+Hall+St%2C+Knox%2FHenderson", tags: ["Walkable", "Knox", "Free"] },
  { cat: 'activities', name: "White Rock Lake Park", rating: 4.8, count: 5087, price: 1, address: "8300 E Lawther Dr, East Dallas", note: "9-mile loop trail around the lake. Best for biking, long walks, sunset photos. Dog-friendly. 15 min drive from Highland Park. Open 5am-11pm. Bring water — limited shade.", maps: "https://www.google.com/maps/search/?api=1&query=White+Rock+Lake+Park%2C+8300+E+Lawther+Dr%2C+East+Dallas", tags: ["Lake", "Biking", "Sunset"] },
  { cat: 'activities', name: "Dallas Farmers Market", rating: 4.5, count: 10342, price: 2, address: "920 S Harwood St, Downtown", note: "Indoor food hall + outdoor weekend market. Daily 10am-7pm. The Shed is open Sat 9-5, Sun 10-5 — that's when local farmers set up. Combine with brunch and a walk around downtown.", maps: "https://www.google.com/maps/search/?api=1&query=Dallas+Farmers+Market%2C+920+S+Harwood+St%2C+Downtown", tags: ["Food hall", "Saturdays", "Local"] },
  { cat: 'activities', name: "Bishop Arts District", rating: 4.7, count: 1000, price: 2, address: "Bishop Arts District, Oak Cliff", note: "Walkable neighborhood across the river. Indie boutiques, bookshops, murals, restaurants. Best for a 2-3 hr afternoon stroll. Weekends are crowded but lively. Park on side streets, walk Bishop Ave.", maps: "https://www.google.com/maps/search/?api=1&query=Bishop+Arts+District%2C+Bishop+Arts+District%2C+Oak+Cliff", tags: ["Walkable", "Boutiques", "Murals"] },
];

const FOOD_CATS = [
  { id: 'italian',  label: 'Italian',       icon: '🍝', desc: 'Pasta + Italian',              num: '01' },
  { id: 'pizza',    label: 'Pizza',          icon: '🍕', desc: 'Pies + slices',                num: '02' },
  { id: 'asian',    label: 'Asian / Sushi',  icon: '🍜', desc: 'Ramen, sushi, Japanese, Asian', num: '03' },
  { id: 'mexican',  label: 'Mexican',        icon: '🌮', desc: 'Tacos + cantina',              num: '04' },
  { id: 'american', label: 'American',       icon: '🥘', desc: 'New American + bistros',       num: '05' },
  { id: 'steaks',   label: 'Steaks',         icon: '🥩', desc: 'Steakhouse + tasting menu',    num: '06' },
  { id: 'bbq',      label: 'BBQ',            icon: '🔥', desc: 'Texas barbecue',               num: '07' },
  { id: 'healthy',  label: 'Healthy',        icon: '🥗', desc: 'Bowls, salads, real food',     num: '08' },
  { id: 'fastfood', label: 'Fast Food',      icon: '🍔', desc: 'Quick + dirty + good',         num: '09' },
];

const REST_CATS = [
  { id: 'coffee',     label: 'Coffee',     icon: '☕',  desc: 'Working & casual hangs',          num: '10' },
  { id: 'nightlife',  label: 'Nightlife',  icon: '🍸',  desc: 'Bars, clubs, late nights',        num: '11' },
  { id: 'activities', label: 'Activities', icon: '🎳',  desc: 'Bowling, golf, museums, walks',   num: '12' },
  { id: 'gym',        label: 'Gym',        icon: '🏋️', desc: 'Lift & sweat',                    num: '13' },
  { id: 'barber',     label: 'Barber',     icon: '✂️',  desc: 'Cuts & grooming',                 num: '14' },
  { id: 'wellness',   label: 'Wellness',   icon: '💆',  desc: 'Spa, nails, massage',             num: '15' },
  { id: 'healthcare', label: 'Healthcare', icon: '⚕️',  desc: 'Doctors, dentist, ER, pharmacy',  num: '16' },
  { id: 'grocery',    label: 'Grocery',    icon: '🛒',  desc: 'Stocking the kitchen',            num: '17' },
];

const ALL_CATS = [...FOOD_CATS, ...REST_CATS];
